<?php

use Illuminate\Database\Seeder;

class GigPricesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('gig_prices')->delete();
        
        \DB::table('gig_prices')->insert(array (
            0 => 
            array (
                'id' => 2,
                'gig_id' => 2,
                'basic_package_name' => 'BASIC',
                'standard_package_name' => 'Pro',
                'premium_package_name' => 'ULTIMATE',
            'basic_description' => '- 3 Concepts, Professional Logo Design + All the files (.AI, .PNG,PDF etc.)+Unlimited Revisions',
                'standard_description' => '-Logo Design
-Business Card

Formats:
.ai .pdf .jpeg .png .eps .psd',
                'premium_description' => '-Logo 
-Business Card
-Brand Guide

Formats:
.ai .pdf .jpeg .png .eps .psd',
                'basic_delivery_time' => '1',
                'standard_delivery_time' => '2',
                'premium_delivery_time' => '3',
                'basic_price' => '15.00',
                'standard_price' => '60.00',
                'premium_price' => '220.00',
                'status' => 1,
            ),
            1 => 
            array (
                'id' => 4,
                'gig_id' => 4,
                'basic_package_name' => 'FORTNITE 1 HOUR COACHING. PUBS ONL',
                'standard_package_name' => 'FORTNITE 2 HOUR COACHING',
                'premium_package_name' => 'FORTNITE WEEK LONG COACH',
                'basic_description' => 'I will play with you for 1 hour and give you pro tips on how to win public games and arenas.',
                'standard_description' => 'I will play with you for 2 hours and do creative tips and public games.',
                'premium_description' => 'I will play with you almost everyday a week and give you pro tips on how to win scrims and build.',
                'basic_delivery_time' => '1',
                'standard_delivery_time' => '2',
                'premium_delivery_time' => '3',
                'basic_price' => '10.00',
                'standard_price' => '50.00',
                'premium_price' => '100.00',
                'status' => 1,
            ),
            2 => 
            array (
                'id' => 7,
                'gig_id' => 7,
                'basic_package_name' => 'fggggggggggq',
                'standard_package_name' => 'gffdddddddddddddddddd',
                'premium_package_name' => 'dffffffffffffffffffff',
                'basic_description' => 'fffffffffffffffffffffffffffff',
                'standard_description' => 'fffffffffffffffffffffffffffffff',
                'premium_description' => 'fffffffffffffffffffffff',
                'basic_delivery_time' => '2',
                'standard_delivery_time' => '4',
                'premium_delivery_time' => '6',
                'basic_price' => '5.00',
                'standard_price' => '5.00',
                'premium_price' => '5.00',
                'status' => 1,
            ),
            3 => 
            array (
                'id' => 8,
                'gig_id' => 1,
                'basic_package_name' => 'uuuuuuuu',
                'standard_package_name' => NULL,
                'premium_package_name' => NULL,
                'basic_description' => 'dsfdsf',
                'standard_description' => NULL,
                'premium_description' => NULL,
                'basic_delivery_time' => '4',
                'standard_delivery_time' => '4',
                'premium_delivery_time' => '7',
                'basic_price' => '5.00',
                'standard_price' => '5.00',
                'premium_price' => '5.00',
                'status' => 1,
            ),
            4 => 
            array (
                'id' => 10,
                'gig_id' => 9,
                'basic_package_name' => 'Basic',
                'standard_package_name' => 'Standard',
                'premium_package_name' => 'Premium',
                'basic_description' => 'small bug fix up to two hours work',
                'standard_description' => 'Basic website up to 5 pages',
                'premium_description' => 'Any kind of complex problem up to 10 days works',
                'basic_delivery_time' => '1',
                'standard_delivery_time' => '6',
                'premium_delivery_time' => '10',
                'basic_price' => '15.00',
                'standard_price' => '240.00',
                'premium_price' => '525.00',
                'status' => 1,
            ),
            5 => 
            array (
                'id' => 11,
                'gig_id' => 10,
                'basic_package_name' => 'BASIC PACKAGE',
                'standard_package_name' => 'NORMAL PACKAGE',
                'premium_package_name' => 'PRO PACKAGE',
                'basic_description' => '2Logo concept,HighResolution JPEG+source file+unlimited revisions.',
                'standard_description' => '4Logo concept+ HighResolution JPEG,PNG,PDF+ Source,Vector+ UnlimitedRevisions.',
                'premium_description' => NULL,
                'basic_delivery_time' => '3',
                'standard_delivery_time' => '6',
                'premium_delivery_time' => '5',
                'basic_price' => '25.00',
                'standard_price' => '45.00',
                'premium_price' => '105.00',
                'status' => 1,
            ),
            6 => 
            array (
                'id' => 12,
                'gig_id' => 11,
                'basic_package_name' => 'SILVER PACKAGE',
                'standard_package_name' => 'GOLD PACKAGE',
                'premium_package_name' => 'PLATINUM PACKAGE',
                'basic_description' => '1 signature Logo 300 dpi + high resolution JPEG + LOGO TRANSPARENCY PNG. NO DRAWINGS',
                'standard_description' => '1 Main logo + 1 watermark Logo + Full HD JPEG and PNG Files + DRAWINGS/ILLUSTRATIONS',
                'premium_description' => '1 Main logo +1 Alternate logo +1 watermark +PNG+JPEG+vector file + 4 revisions. DRAWINGS',
                'basic_delivery_time' => '2',
                'standard_delivery_time' => '1',
                'premium_delivery_time' => '1',
                'basic_price' => '5.00',
                'standard_price' => '20.00',
                'premium_price' => '45.00',
                'status' => 1,
            ),
            7 => 
            array (
                'id' => 13,
                'gig_id' => 12,
                'basic_package_name' => 'INITIAL PACKAGE',
                'standard_package_name' => 'STANDARD PACKAGE - TOP SELLING',
                'premium_package_name' => 'PREMIUM PACKAGE - FOR EXCLUSIVES !',
            'basic_description' => '2 logo design along with white and transparent background (JPEG PNG) Files',
                'standard_description' => '2 HQ Creative variation with JPEG PNG + SOCIAL MEDIA COVERS + .ai .eps SOURCE VECTOR Files',
                'premium_description' => '3 Highly Professional variations JPEG PNG + STATIONARY & SOCIAL MEDIA DESIGN + Source files for logo',
                'basic_delivery_time' => '2',
                'standard_delivery_time' => '1',
                'premium_delivery_time' => '1',
                'basic_price' => '5.00',
                'standard_price' => '20.00',
                'premium_price' => '65.00',
                'status' => 1,
            ),
            8 => 
            array (
                'id' => 14,
                'gig_id' => 13,
                'basic_package_name' => 'OBJECT LOGO',
                'standard_package_name' => 'MASCOT LOGO',
                'premium_package_name' => 'PEOPLE LOGO',
            'basic_description' => '(Extra objects have additional cost) Unlimited revisions until the order has been competed.',
            'standard_description' => '(Extra characters have additional cost) Unlimited revisions until the order has been competed.',
            'premium_description' => '(Extra people have additional cost) Unlimited revisions until the order has been competed.',
                'basic_delivery_time' => '2',
                'standard_delivery_time' => '4',
                'premium_delivery_time' => '4',
                'basic_price' => '15.00',
                'standard_price' => '45.00',
                'premium_price' => '95.00',
                'status' => 1,
            ),
            9 => 
            array (
                'id' => 15,
                'gig_id' => 14,
                'basic_package_name' => 'COPPER',
                'standard_package_name' => 'SILVER',
                'premium_package_name' => 'GOLD',
            'basic_description' => '2 Basic Designs with JPG & PNG (only basic designs, no complex or mascot design)',
            'standard_description' => '3 HQ Logo with All Editable & Printable Files (Most Recommended Pack)',
                'premium_description' => '5 HQ Designs + All Editable & Printable Files + Social Media Kit + Business Card + Stationery Design',
                'basic_delivery_time' => '1',
                'standard_delivery_time' => '2',
                'premium_delivery_time' => '3',
                'basic_price' => '15.00',
                'standard_price' => '35.00',
                'premium_price' => '70.00',
                'status' => 1,
            ),
            10 => 
            array (
                'id' => 16,
                'gig_id' => 15,
                'basic_package_name' => '1 LOGO CONCEPT',
                'standard_package_name' => '2 LOGO CONCEPT',
                'premium_package_name' => '3 LOGO CONCEPT',
                'basic_description' => 'Includes 3 logo design concepts, we will finalize the one you will choose + All Source files + Codes',
                'standard_description' => 'Includes 2 logo design concepts, we will finalize the one you will choose + All Source files + Codes',
                'premium_description' => 'Includes 3 logo design concepts, we will finalize the one you will choose + All Source files + Codes',
                'basic_delivery_time' => '3',
                'standard_delivery_time' => '5',
                'premium_delivery_time' => '7',
                'basic_price' => '40.00',
                'standard_price' => '75.00',
                'premium_price' => '95.00',
                'status' => 1,
            ),
            11 => 
            array (
                'id' => 17,
                'gig_id' => 16,
                'basic_package_name' => 'Basic',
                'standard_package_name' => 'Standard',
                'premium_package_name' => 'Premium',
                'basic_description' => 'The Basic Catalogue Design Service',
                'standard_description' => 'Get a Standard Catalogue with 3 revisions.',
                'premium_description' => 'Get premium Catalogue with unlimited revisions.',
                'basic_delivery_time' => '10',
                'standard_delivery_time' => '12',
                'premium_delivery_time' => '15',
                'basic_price' => '5.00',
                'standard_price' => '10.00',
                'premium_price' => '15.00',
                'status' => 1,
            ),
            12 => 
            array (
                'id' => 18,
                'gig_id' => 17,
                'basic_package_name' => 'Type 1 Flyer',
                'standard_package_name' => 'Type 2 Flyer',
                'premium_package_name' => 'Type 3 Flyer',
                'basic_description' => 'The basic Flyer, no revision.',
                'standard_description' => 'Flyer that you want with 3 revisions.',
                'premium_description' => 'Absolutely stunning Flyer with unlimited revisions.',
                'basic_delivery_time' => '6',
                'standard_delivery_time' => '10',
                'premium_delivery_time' => '12',
                'basic_price' => '10.00',
                'standard_price' => '15.00',
                'premium_price' => '20.00',
                'status' => 1,
            ),
            13 => 
            array (
                'id' => 19,
                'gig_id' => 18,
                'basic_package_name' => 'Basic Logo Animation',
                'standard_package_name' => 'Standard Logo Animation',
                'premium_package_name' => 'Stunning High Quality Logo Animatio',
                'basic_description' => 'There will be 3 second logo animation in standard quality.',
                'standard_description' => 'There will be 5 seconds logo animation in high quality.',
                'premium_description' => 'Five to ten seconds logo animation in Super HD Quality.',
                'basic_delivery_time' => '3',
                'standard_delivery_time' => '7',
                'premium_delivery_time' => '9',
                'basic_price' => '20.00',
                'standard_price' => '30.00',
                'premium_price' => '35.00',
                'status' => 1,
            ),
            14 => 
            array (
                'id' => 20,
                'gig_id' => 19,
                'basic_package_name' => 'Basic Sales Copy',
                'standard_package_name' => 'Standard Sales Copy',
                'premium_package_name' => 'Premium Sales Copy',
                'basic_description' => 'A sharp little jet of copy to jumpstart conversions.',
                'standard_description' => 'A headshot of potent content that nails pain points and proves that you can solve problems.',
                'premium_description' => 'An iron grip of science-backed persuasion, wrapped in sexy, breezy copy. Won\'t know what hit \'em.',
                'basic_delivery_time' => '7',
                'standard_delivery_time' => '10',
                'premium_delivery_time' => '15',
                'basic_price' => '100.00',
                'standard_price' => '230.00',
                'premium_price' => '500.00',
                'status' => 1,
            ),
            15 => 
            array (
                'id' => 21,
                'gig_id' => 20,
                'basic_package_name' => 'Gold',
                'standard_package_name' => 'Diamond',
                'premium_package_name' => 'Platinum',
                'basic_description' => 'Get the Sales Copy that converts for all industries.',
                'standard_description' => 'Exclusively written for you',
                'premium_description' => 'On demand Sales copywriting',
                'basic_delivery_time' => '7',
                'standard_delivery_time' => '12',
                'premium_delivery_time' => '15',
                'basic_price' => '50.00',
                'standard_price' => '75.00',
                'premium_price' => '100.00',
                'status' => 1,
            ),
            16 => 
            array (
                'id' => 22,
                'gig_id' => 21,
                'basic_package_name' => 'On-Page SEO',
                'standard_package_name' => 'Off-Page SEO',
                'premium_package_name' => 'Guaranteed Ranking',
                'basic_description' => 'We fix Title, Meta, URL and Keywords in content to make your site SEO Friendly.',
                'standard_description' => 'Off Page SEO and link building to boost the ranking of your site.',
                'premium_description' => 'On-Page, Off-Page SEO along with several other activities to provide you guaranteed ranking.',
                'basic_delivery_time' => '7',
                'standard_delivery_time' => '20',
                'premium_delivery_time' => '30',
                'basic_price' => '300.00',
                'standard_price' => '550.00',
                'premium_price' => '1000.00',
                'status' => 1,
            ),
            17 => 
            array (
                'id' => 23,
                'gig_id' => 22,
                'basic_package_name' => 'Weekly Package',
                'standard_package_name' => 'Monthly Package',
                'premium_package_name' => 'Quarterly',
                'basic_description' => '5 highly engaging Posts per day on Facebook, Twitter, Linkedin, Instagram for 1 week.',
                'standard_description' => '5 highly engaging Posts per day on Facebook, Twitter, Linkedin, Instagram for 30 days.',
                'premium_description' => '5 highly engaging Posts per day on Facebook, Twitter, Linkedin, Instagram, and Youtube for 3 months.',
                'basic_delivery_time' => '5',
                'standard_delivery_time' => '15',
                'premium_delivery_time' => NULL,
                'basic_price' => '5.00',
                'standard_price' => '10.00',
                'premium_price' => '30.00',
                'status' => 1,
            ),
            18 => 
            array (
                'id' => 24,
                'gig_id' => 23,
                'basic_package_name' => 'Small piece',
                'standard_package_name' => 'Medium Length Article',
                'premium_package_name' => 'Long piece',
                'basic_description' => 'I will write up to 350-500 words about any topic',
                'standard_description' => '500-1000 words on any topic with some research but not including referencing',
                'premium_description' => '1000-3000 words on any topic with thorough research and referencing',
                'basic_delivery_time' => '1',
                'standard_delivery_time' => '2',
                'premium_delivery_time' => '3',
                'basic_price' => '10.00',
                'standard_price' => '30.00',
                'premium_price' => '40.00',
                'status' => 1,
            ),
            19 => 
            array (
                'id' => 25,
                'gig_id' => 24,
                'basic_package_name' => 'Short',
                'standard_package_name' => 'Medium',
                'premium_package_name' => 'Long',
                'basic_description' => '350-500 words',
                'standard_description' => '500-1000 words',
                'premium_description' => '1000-3000',
                'basic_delivery_time' => '1',
                'standard_delivery_time' => '2',
                'premium_delivery_time' => '3',
                'basic_price' => '5.00',
                'standard_price' => '5.00',
                'premium_price' => '5.00',
                'status' => 1,
            ),
            20 => 
            array (
                'id' => 26,
                'gig_id' => 25,
                'basic_package_name' => 'Facebook',
                'standard_package_name' => 'Facebook and other social medias',
                'premium_package_name' => 'Facebook and other social medias',
                'basic_description' => 'Facebook, Twitter & Instagram 5 Posts per week',
                'standard_description' => 'Facebook, Twitter, Google My Business Page, Instagram & Pinterest 5 Posts per week 1 month',
                'premium_description' => 'Facebook, Twitter & Instagram 5 Posts per week',
                'basic_delivery_time' => '1',
                'standard_delivery_time' => '2',
                'premium_delivery_time' => '3',
                'basic_price' => '5.00',
                'standard_price' => '15.00',
                'premium_price' => '35.00',
                'status' => 1,
            ),
            21 => 
            array (
                'id' => 27,
                'gig_id' => 27,
                'basic_package_name' => 'Basic SEM',
                'standard_package_name' => 'Standard SEM',
                'premium_package_name' => 'Premium SEM',
                'basic_description' => 'Basic Search Engine Marketing Services.',
                'standard_description' => 'Standard Search Engine Marketing Services.',
                'premium_description' => 'Premimum Search Engine Marketing Services.',
                'basic_delivery_time' => '10',
                'standard_delivery_time' => '20',
                'premium_delivery_time' => '30',
                'basic_price' => '30.00',
                'standard_price' => '50.00',
                'premium_price' => '120.00',
                'status' => 1,
            ),
            22 => 
            array (
                'id' => 28,
                'gig_id' => 28,
                'basic_package_name' => 'The Basic Video Marketing.',
                'standard_package_name' => 'Standard Digital Video Marketing.',
                'premium_package_name' => 'Advanced Video Marketing with Tools',
                'basic_description' => 'Video Promotion on different platforms.',
                'standard_description' => 'Standard Video Promotion through our specialised services.',
                'premium_description' => 'Professional organic top youtube video promotion to make your video go viral',
                'basic_delivery_time' => '7',
                'standard_delivery_time' => '18',
                'premium_delivery_time' => '29',
                'basic_price' => '30.00',
                'standard_price' => '70.00',
                'premium_price' => '200.00',
                'status' => 1,
            ),
        ));
        
        
    }
}